global:
  scrape_interval:     10s
 
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9100"]
